# Generated by Django 4.1.3 on 2022-11-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroc', '0002_subscriber_is_subscribed_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'staff categories',
            },
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_subscribed_sms',
            field=models.BooleanField(default=False, verbose_name='Subscribe To SMS Alerts'),
        ),
    ]
