# Generated by Django 4.1.3 on 2022-11-18 18:51

from django.db import migrations, models
import django_aroc.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('aroc', '0004_page_staff_category_staff_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('button_text', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, null=True, storage=django_aroc.storage_backends.PublicMediaStorage(), upload_to='img/')),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.TextField(blank=True)),
                ('donate_text', models.TextField(blank=True)),
                ('newsletter_text', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('donate_link', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('category',), 'verbose_name_plural': 'staff'},
        ),
        migrations.AlterModelOptions(
            name='staffcategory',
            options={'ordering': ('order_id',), 'verbose_name_plural': 'staff categories'},
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_aroc.storage_backends.PublicMediaStorage(), upload_to='img/'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
