# Generated by Django 4.1.3 on 2022-11-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroc', '0005_feature_overview_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aroc.page'),
        ),
    ]
